FROM nikolaik/python-nodejs:python3.7-nodejs12
LABEL org.opencontainers.image.source https://github.com/simcesplatform/simulation-manager
LABEL org.opencontainers.image.description "Docker image for the dummy component. Docker image source: Dockerfile-dummy"

RUN mkdir -p /dummy
RUN mkdir -p /init
RUN mkdir -p /logs
RUN mkdir -p /simulation-tools

# install the python libraries
COPY requirements.txt /requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /requirements.txt

# install the Node.js libraries
# this is required when using the time series classes and units which are not given in the premade list
COPY package.json /package.json
RUN npm install -g

COPY dummy/ /dummy/
COPY init/ /init/
COPY simulation-tools/ /simulation-tools/

WORKDIR /

CMD [ "python3", "-u", "-m", "dummy.dummy" ]
