FROM nikolaik/python-nodejs:python3.7-nodejs12

RUN mkdir -p /tests/dummy
RUN mkdir -p /tests/init
RUN mkdir -p /tests/listener
RUN mkdir -p /tests/manager
RUN mkdir -p /tests/simulation-tools

# install the Python libraries
COPY requirements.txt /requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /requirements.txt

# install the Node.js libraries
# this is required when using the time series classes and units which are not given in the premade list
COPY package.json /package.json
RUN npm install -g

COPY dummy/ /tests/dummy/
COPY init/ /tests/init/
COPY listener/ tests/listener/
COPY manager/ /tests/manager/
COPY simulation-tools/ /tests/simulation-tools/

WORKDIR /tests

CMD [ "python3", "-u", "-m", "unittest", "discover", "-s", ".", "-p", "*.py" ]
