FROM python:3.7.9

RUN mkdir -p /init
RUN mkdir -p /listener
RUN mkdir -p /logs
RUN mkdir -p /simulation-tools

COPY requirements.txt /requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /requirements.txt

COPY init/ /init/
COPY listener/ /listener/
COPY simulation-tools/ /simulation-tools/

WORKDIR /

CMD [ "python3", "-u", "-m", "listener.listener" ]
