version: '3.5'

services:

  log_writer:
    build:
      context: .
      dockerfile: Dockerfile-logwriter
    image: log_writer:1.0.4
    container_name: log_writer
    restart: "no"
    env_file:
      - log_writer.env
    volumes:
      - log_writer_logs:/logs
    networks:
      - mongodb_network
      - rabbitmq_network

volumes:
  log_writer_logs:
    name: log_writer_logs

networks:
  mongodb_network:
    external: true
    name: mongodb_network

  rabbitmq_network:
    external: true
    name: rabbitmq_network
