version: '3.5'

services:

  mongodb:
    image: mongo:4.2.7
    container_name: mongodb_tools_tests
    restart: always
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=testuser
      - MONGO_INITDB_ROOT_PASSWORD=testpass
    networks:
      - tools_test_network

networks:
  tools_test_network:
    external: true
    name: tools_test_network
