version: '3.5'

services:

  rabbitmq:
    image: rabbitmq:3.8.4-management
    container_name: rabbitmq_tools_tests
    restart: always
    expose:
      - 5672
    environment:
      - RABBITMQ_EXCHANGE=procem.tools_tests
    networks:
      - tools_test_network

networks:
  tools_test_network:
    external: true
    name: tools_test_network
